spring.application.name=Garage Management System
spring.datasource.url=jdbc:mysql://localhost:3306/garage_db
spring.datasource.username=root
spring.datasource.password=Dhan@0309Pooja

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Swagger/OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Server Port
server.port=8080